### ISSUE TITLE
User can't mark a day on the calendar that has passed, but can mark start time that has passed

### ISSUE THREAD

**Issue by ivandimov** [Team-Rookies/NBU-Library-Reservation-System#14]
For example Now is 2/9/2016, 20:20 user is able to create an event on 2/9/2016  with start time 9:00. Times that has passed should be grayed out too.

**Comment by BogomilDimitrov** [comment]
Fixed d13d1b5b2fbb77daa97ecc2b663d117ecced24d8 !
